return {
  {
    "williamboman/mason.nvim",
    build = ":MasonUpdate",
    opts = {},
  },
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    dependencies = { "williamboman/mason.nvim" },
    opts = {
      ensure_installed = {
        "clangd",
        "lua-language-server",
        "stylua",
        "codelldb",
        "rust-analyzer",
        "pyright",
        "bash-language-server",
        "typescript-language-server",
        "html-lsp",
        "css-lsp",
        "json-lsp",
        "yaml-language-server",
        "gopls",
        "marksman",
        "taplo",
        "clang-format",
        "black",
        "isort",
        "prettierd",
        "shfmt",
        "goimports",
      },
      automatic_installation = true,
    },
  },
}
