return {
--   "folke/noice.nvim",
--   event = "VeryLazy",
--   dependencies = {
--     "MunifTanjim/nui.nvim",
--     "rcarriga/nvim-notify",
--   },
--   opts = {
--     -- Tu peux personnaliser ici, exemple :
--     lsp = {
--       progress = { enabled = true },
--       signature = { enabled = true },
--       hover = { enabled = true },
--       message = { enabled = true },
--     },
--     presets = {
--       bottom_search = true,
--       command_palette = true,
--       long_message_to_split = true,
--       inc_rename = false,
--       lsp_doc_border = true,
--     },
--   },
}