return {
    require("plugins.treesitter"),
    require("plugins.snacks"),
    require("plugins.mason"),
    require("plugins.telescope"),
    require("plugins.nvim-cmp"),
    require("plugins.lualine"),
    require("plugins.cyberdream"),
    require("plugins.oxocarbon"),
    require("plugins.dracula"),
    require("plugins.ayu-vim"),
    require("plugins.nvim-tree"),
    require("plugins.vscode-colors"),
    -- require("plugins.noice"), -- NAH
    require("plugins.harpoon"),
    require("plugins.lspconfig"),
    require("plugins.lsp_signature"),
    require("plugins.luasnip"),
    require("plugins.autopairs"),
    require("plugins.undotree"),
    require("plugins.noirblaze"),
    require("plugins.sunbather"),
    require("plugins.pinkmare"),
    require("plugins.epi-quickfix"),
    require("plugins.bufferline.lua"),
    require("plugins.oil"),
    require("plugins.hover"),
    require("plugins.lspsaga"),
    -- Add devicons so icons show up across UI components
    require("plugins.devicons"),
}
